#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# deploy-test-suite.sh
#
# Builds and deploys all Soroban contracts found in the contracts/ directory
# to a running standalone (local) Stellar network, then writes the generated
# Contract IDs to apps/web/.env.local for frontend consumption.
# =============================================================================

# ---------------------------------------------------------------------------
# Configuration — override via environment variables if needed
# ---------------------------------------------------------------------------
CONTRACTS_DIR="${CONTRACTS_DIR:-./contracts}"
ENV_OUTPUT="${ENV_OUTPUT:-./apps/web/.env.local}"
NETWORK="${NETWORK:-standalone}"
RPC_URL="${RPC_URL:-http://localhost:8000/soroban/rpc}"
NETWORK_PASSPHRASE="${NETWORK_PASSPHRASE:-Standalone Network ; February 2017}"
SOURCE_ACCOUNT="${SOURCE_ACCOUNT:-alice}"

# ---------------------------------------------------------------------------
# Colour helpers
# ---------------------------------------------------------------------------
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Colour

info()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------
if ! command -v stellar &> /dev/null; then
  error "stellar CLI not found. Install it from https://stellar.org/developers/tools"
  exit 1
fi

if ! command -v cargo &> /dev/null; then
  error "cargo not found. Install Rust from https://rustup.rs"
  exit 1
fi

if [ ! -d "$CONTRACTS_DIR" ]; then
  error "Contracts directory '$CONTRACTS_DIR' does not exist."
  exit 1
fi

# ---------------------------------------------------------------------------
# Prepare output file
# ---------------------------------------------------------------------------
mkdir -p "$(dirname "$ENV_OUTPUT")"

# Write a fresh header — existing entries are replaced on each run
cat > "$ENV_OUTPUT" << 'EOF'
# Auto-generated by scripts/deploy-test-suite.sh
# Do not edit manually — re-run `npm run deploy:contracts` to regenerate.

EOF

info "Output will be written to: $ENV_OUTPUT"
info "Network:    $NETWORK ($RPC_URL)"
info "Source:     $SOURCE_ACCOUNT"
echo ""

# ---------------------------------------------------------------------------
# Iterate over every subdirectory of contracts/
# ---------------------------------------------------------------------------
SUCCESS_COUNT=0
FAIL_COUNT=0

for CONTRACT_PATH in "$CONTRACTS_DIR"/*/; do
  # Skip if nothing matched (empty directory)
  [ -d "$CONTRACT_PATH" ] || continue

  CONTRACT_NAME="$(basename "$CONTRACT_PATH")"

  # Skip directories that don't look like Rust crates
  if [ ! -f "$CONTRACT_PATH/Cargo.toml" ]; then
    warn "Skipping '$CONTRACT_NAME' — no Cargo.toml found."
    continue
  fi

  info "Processing contract: $CONTRACT_NAME"

  # ------------------------------------------------------------------
  # 1. Build
  # ------------------------------------------------------------------
  info "  Building $CONTRACT_NAME..."
  if ! stellar contract build --manifest-path "$CONTRACT_PATH/Cargo.toml" 2>&1; then
    error "  Build failed for $CONTRACT_NAME — skipping deployment."
    FAIL_COUNT=$((FAIL_COUNT + 1))
    continue
  fi

  # Resolve the compiled WASM path.
  # stellar contract build places the output in target/wasm32-unknown-unknown/release/
  WASM_NAME="${CONTRACT_NAME//-/_}.wasm"
  WASM_PATH="./target/wasm32-unknown-unknown/release/$WASM_NAME"

  if [ ! -f "$WASM_PATH" ]; then
    # Some crates produce a differently-cased file — do a case-insensitive search
    WASM_PATH=$(find ./target/wasm32-unknown-unknown/release/ -maxdepth 1 -iname "${CONTRACT_NAME//-/_}.wasm" | head -n 1 || true)
  fi

  if [ -z "$WASM_PATH" ] || [ ! -f "$WASM_PATH" ]; then
    error "  Could not locate compiled WASM for $CONTRACT_NAME."
    FAIL_COUNT=$((FAIL_COUNT + 1))
    continue
  fi

  info "  WASM: $WASM_PATH"

  # ------------------------------------------------------------------
  # 2. Deploy
  # ------------------------------------------------------------------
  info "  Deploying $CONTRACT_NAME..."
  DEPLOY_OUTPUT=$(stellar contract deploy \
    --wasm "$WASM_PATH" \
    --source "$SOURCE_ACCOUNT" \
    --network "$NETWORK" \
    --rpc-url "$RPC_URL" \
    --network-passphrase "$NETWORK_PASSPHRASE" \
    2>&1) || {
    error "  Deploy failed for $CONTRACT_NAME:"
    error "  $DEPLOY_OUTPUT"
    FAIL_COUNT=$((FAIL_COUNT + 1))
    continue
  }

  # The stellar CLI prints the Contract ID as the last non-empty line
  CONTRACT_ID=$(echo "$DEPLOY_OUTPUT" | grep -E '^C[A-Z0-9]{55}$' | tail -n 1 || true)

  if [ -z "$CONTRACT_ID" ]; then
    # Fallback: grab the last non-empty line
    CONTRACT_ID=$(echo "$DEPLOY_OUTPUT" | awk 'NF' | tail -n 1)
  fi

  if [ -z "$CONTRACT_ID" ]; then
    error "  Could not parse Contract ID from deploy output for $CONTRACT_NAME."
    error "  Raw output: $DEPLOY_OUTPUT"
    FAIL_COUNT=$((FAIL_COUNT + 1))
    continue
  fi

  # ------------------------------------------------------------------
  # 3. Write to .env.local
  # ------------------------------------------------------------------
  # Convert contract name to SCREAMING_SNAKE_CASE env var:
  # e.g. source-registry -> NEXT_PUBLIC_CONTRACT_SOURCE_REGISTRY
  ENV_KEY="NEXT_PUBLIC_CONTRACT_$(echo "$CONTRACT_NAME" | tr '[:lower:]-' '[:upper:]_')"

  echo "${ENV_KEY}=${CONTRACT_ID}" >> "$ENV_OUTPUT"

  info "  Contract ID: $CONTRACT_ID"
  info "  Env var:     $ENV_KEY"
  echo ""

  SUCCESS_COUNT=$((SUCCESS_COUNT + 1))
done

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo "============================================"
info "Deployment complete."
info "  Succeeded: $SUCCESS_COUNT"
[ "$FAIL_COUNT" -gt 0 ] && error "  Failed:    $FAIL_COUNT" || info "  Failed:    $FAIL_COUNT"
echo "============================================"
echo ""
info "Contract IDs written to: $ENV_OUTPUT"
echo ""
cat "$ENV_OUTPUT"